In [43]:
from math import *
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.linalg as lin

In [395]:
N = 12
D = N//2
mymat = np.matrix([[(1-np.cos(2 * np.pi * i * j / N))/(1-np.cos(2 * np.pi * j / N)) 
            for j in range(1,D+1)] for i in range(1,D+1)])


symmat = mymat*mymat.T
print(mymat)
#print(symmat)
#print(lin.norm(lin.eig(symmat)[1][:,0]))


## det(M) = N^((D-1)/2)*(2Ind_{n == 0,1,2,3 mod8}(N) - 1)
#print(lin.det(mymat))
#print(log(abs(lin.det(mymat)),N))
#print(N**((D-1)/2))

## Note the sum of the rows
#ones = np.matrix(np.ones((D,1)))
#print(mymat*ones)

[[  1.           1.           1.           1.           1.           1.        ]
 [  3.73205081   3.           2.           1.           0.26794919   0.        ]
 [  7.46410162   4.           1.           0.           0.53589838   1.        ]
 [ 11.19615242   3.           0.           1.           0.80384758   0.        ]
 [ 13.92820323   1.           1.           1.           0.07179677   1.        ]
 [ 14.92820323   0.           2.           0.           1.07179677   0.        ]]


In [374]:
N = 12
D = N//2
mymat = np.matrix([[(1-np.cos(2 * np.pi * i * j / N)) for j in range(1,D+1)] for i in range(1,D+1)])

mydenom = np.matrix([[(1-np.cos(2 * np.pi * j / N)) for j in range(1,D+1)]])
print(np.prod(mydenom))


print(mymat.round(3))
symmat = mymat*mymat.T
print(symmat)

print(lin.det(symmat))
print(N**((D-1)/2.))
print(N**((D-1)/2.)*(np.prod(mydenom)**2))
print(lin.eig(symmat)[0][0].round(3).real)
#((lin.eig(symmat)[0][0])*np.matrix(lin.eig(symmat)[1][:,0]).T*np.matrix(lin.eig(symmat)[1][:,0])).round(3).real
((lin.eig(mymat)[0][0])*np.matrix(lin.eig(mymat)[1][:,0]).T*np.matrix(lin.eig(mymat)[1][:,0])).round(3).real
lin.logm(symmat).round(3)
print(2**(-D+3) * D**(D+1))

0.375
[[ 0.134  0.5    1.     1.5    1.866  2.   ]
 [ 0.5    1.5    2.     1.5    0.5    0.   ]
 [ 1.     2.     1.     0.     1.     2.   ]
 [ 1.5    1.5    0.     1.5    1.5    0.   ]
 [ 1.866  0.5    1.     1.5    0.134  2.   ]
 [ 2.     0.     2.     0.     2.     0.   ]]
[[ 11.   6.   8.   6.   8.   6.]
 [  6.   9.   6.   6.   6.   6.]
 [  8.   6.  11.   6.   8.   6.]
 [  6.   6.   6.   9.   6.   6.]
 [  8.   6.   8.   6.  11.   6.]
 [  6.   6.   6.   6.   6.  12.]]
34991.99999999997
498.8306325798367
70.1480577065
42.696
34992.0


In [369]:
mat = np.matrix([[(i*j)%2 for j in range(1,D+1)] for i in range(1,D+1)])
mat
#lin.eig(symmat)[0].round(2).real
print((2*6)**((6-1)/2.))
print(N**((D-1)/2.))

498.8306325798367
498.8306325798367
